spring:
  application:
    name: ${APP_NAME:weshopify-platform-categories-service}
  profiles:
    active:
    - ${APP_PROFILE_ACTIVE:dev} 
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      format-sql: ${FORMAT_SQL:false}
    
server:
  port: ${APP_PORT:9010}
  
---
spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver 
    url: ${DB_DRIVER:jdbc}:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:weshopify-platform}
    username: ${DB_USER_NAME:root}
    password: ${DB_USER_PWD:root}
---
spring:
  config:
    activate:
      on-profile:
      - qa
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_DRIVER:mem}:${DB_TYPE:h2}:${DB_SCHEMA:weshopify-platform}
    username: admin
    password: admin