spring:
  application:
    name: ${APP_NAME:weshopify-platform-categories-service}
  profiles:
    active:
    - ${PROFILES_ACTIVE:dev}
  jpa:
    show-sql: true

server:
  port: ${APP_PORT:5016}
  
logging:
  file:
    name: weshopify-categories
  level:
    root: info 
      
   #pattern: 
     #level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]"
management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:127.0.0.1}:${ZIPKIN_PORT:9411}/api/v2/spans
      
eureka:
  client:
    fetch-registry: ${FETCH_REGISTRY:true}
    register-with-eureka: ${REGISTER_WITH_REGISTRY:true}
    healthcheck:
      enabled: ${REGISTRY_HEALTH_CHECK:true}
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
  instance:
    hostname: ${SERVICE_REGISTRY_HOST:localhost}
    prefer-ip-address: ${REGISTRY_PREF_IP_ADDR:true}
    
---
spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_PROTOCOL:jdbc}:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:weshopify-categories-db}
    username: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile:
      - qa
  datasource:
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    url: ${DB_PROTOCOL:jdbc}:${DB_TYPE:h2}:${DB_HOST:mem}:${DB_SCHEMA:weshopify-categories-db}
    username: ${DB_USER_NAME:sa}
    password: ${DB_PASSWORD:root}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: ${H2_CONSOLE_PATH:/h2Console}